### PR TITLE
Fixed race condition in getPage

### PR DESCRIPTION
**Pull request by baked-dev**
Sorry for all the small formatting changes my editor made on save. We use this module in a scenario where we run a lot of controlled BrowserViews and sometimes getPage would throw an error because an instance was destroyed after browser.pages got called but before testPage.evaluate got called on that page.

### CODE REVIEW

**Comment by TrevorSundberg** [comment]
Hi baked-dev,

Thanks for your PR. I wanted to mention that you'll have to fix the automatic styling issues because they won't pass the build. We use eslint to lint and make sure formatting is followed.

On the bright side, your PR exposed that our builds stopped! Turns out travis-ci.org is no more as of June 15th, so our builds aren't currently working (hence this PR passing all the checks). Working on getting it re-running, but for now if you want to check yourself you can run `npm run lint` to see the styling errors.

**Comment by baked-dev** [comment]
Hi,

sorry for takiing some time to respond, i had a couple of days off. 

I saw the lint npm script so I ran it before pushing and it only had one warning in a file i hadn't commited. Thats why i thought it would be fine to push. I'll manually fix the styling and resubmit my PR.

**Comment by baked-dev** [comment]
I hope the styling issues are fixed now!

**Comment by TrevorSundberg** [comment]
Thanks for updating it. If you could also fix the newline at the end so it doesn't show up in the diff, I will happily merge this change and push a new version out :)

**Comment by baked-dev** [comment]
Thanks! The newline should be fixed now.

**Comment by TrevorSundberg** [comment]
Merged, thank you so much for this :)

**Comment by TrevorSundberg** [comment]
Just released `3.0.5` on npm!

**Pull request merged**
