### PR TITLE
Used fixed version of sync port finder

### PR DESCRIPTION
**Pull request by PaulBGD**
I also pinned the version of my fixed published package to 1.0.0, as you have no reason to trust a package I've published. Appreciate the fast responses.

### CODE REVIEW

**Comment by PaulBGD** [comment]
I also want to let you know that the `all` script was stopped at the `electron-packager` step.. not sure if it's an issue with my setup. This probably could go into another issue.

**Comment by TrevorSundberg** [comment]
Did you run `npm install`?

**Comment by TrevorSundberg** [comment]
Also thanks for pinning it at 1.0.0, I would have never thought of that as a way of injecting code in the future!

Quick question, it looks like all you did was add the let declaration, what was the original issue? It worked fine for me, was that just a webpack thing that you ran into?

**Comment by PaulBGD** [comment]
I did run `npm install`, all the tests passed.

The issue isn't quite with webpack, it's that if it's running in a strict environment that declaration isn't allowed.

**Comment by TrevorSundberg** [comment]
Sounds good ☺️

**Comment by TrevorSundberg** [comment]
I recently upgraded Ubuntu and realized `netstat` was not installed by default. I think I need to make yet another change again to get rid of the netstat dependency :(

**Comment by TrevorSundberg** [comment]
I just finally decided to "pass the buck" and let the user always pass in the port. So if you want a random port, the user can find a way to synchronously determine the port (or accept the race condition). For now I just used fixed port `14292`.

**Pull request merged**
