### PR TITLE
Don't use a cli tool for ports

### PR DESCRIPTION
**Pull request by PaulBGD**
Pulls in less packages and should be significantly faster.

### CODE REVIEW

**Comment by TrevorSundberg** [comment]
Hi Paul, if you can verify something for me I will gladly merge this pull request.

Basically the issue I have is that there's no guarantee that electron will use the `app.commandLine.appendSwitch` if it's after an `await`. The documentation for this behavior in electron is quite poor, and at my best guess the only way this would 100% work is if electron waited for all microtasks to complete before they use appended command line switches to run their compiled version of Chromium.

That said, the build passed which has me quite confused. I actually originally had the exact code you committed: I was using `getPort`, and then because of the async problem I switched to using the library `deasync` with `getPort`, but then that crashed on some platforms. Eventually I found someone that mentioned if you really needed to run node code synchronously you can put it in another process and then run a synchronous exec child process.

**Comment by PaulBGD** [comment]
That's interesting, I didn't think about that. Actually the reason why I made the change is primarily because it has a shebang at the top of the file, so I had to use a custom loader for webpack. Then It also pulled in a dependency that had more tinkering with webpack, which is when I made this change and tested with the fork.

I'm tempted to say that "since the tests pass, the code works" but I dislike inconsistency as well. Do you think fixing the deasync issues is viable? I'd be willing to put some work into that if so.

**Comment by TrevorSundberg** [comment]
I remember now I never actually ran into this, but I did a test and verified it would be a problem. It repros 100% if you replace `getPort` with a slower version (which could theoretically happen if lots of ports were taken so `getPort` took a long time scanning):

```javascript
const getPortSlow = async () => {
  console.log("wait port");
  await new Promise((resolve) => setTimeout(
    resolve,
    1000
  ));

  console.log("get port");
  return getPort();
};
```

On my machine at 10ms it doesn't happen, but at around 100ms it happens all the time.

I'm trying to rack my brain to remember why `deasync` was crashing, and I feel like it was something to due with running on Windows or running in a container, but I can't remember! This is why I should leave more comments.

I can imagine webpack causing a lot of problems with this (who is requiring the script... etc). As a possible solution is we can write a custom node script that is inline as a string, and then shell exec the entire thing by calling `node`. We would basically have to re-implement getPort however because if we required `"get-port"` we'd run into similar webpack problems.

Another possible idea is to use `--remote-debugging-pipe` instead of `--remote-debugging-port`, though I don't know the full support of that, or if other platforms like Windows will work.

Another option that isn't exactly my favorite is to just pick a port that hopefully never gets used.

I'm going to keep thinking, and I'd love to hear your feedback.

**Comment by TrevorSundberg** [comment]
Potentially found a much better solution, if you pass `--remote-debugging-port 0` Chrome/Electron will automatically pick a port. Now I just need to capture the output somehow and parse it. Or brute force localhost ports until it connects...

**Comment by PaulBGD** [comment]
Yeah so I was just looking into that as well, which seems.. finicky. I'm not sure there's an easy way to get the port besides hijacking the output.

However I did find an existing solution: https://github.com/imwtr/find-free-port-sync
It still uses execSync, however it's essentially a wrapper for `netstat -an` which should be decently compatible.

**Comment by PaulBGD** [comment]
Not sure if you want to go with this route (using a library that parses `netstat -an`) but it does seem decently cross-platform.

**Comment by TrevorSundberg** [comment]
This is great. I just tested it on Mac too and it looks like it works. I was a little worried since the output of netstat on Mac is actually different, but they handled that case too.

**Comment by TrevorSundberg** [comment]
I just published 1.0.8 with the changes :)

**Comment by PaulBGD** [comment]
So that library actually has an error:

https://github.com/imwtr/find-free-port-sync/blob/master/find-free-port-sync.js#L96

That variable is never declared which will fail in strict mode. I'll make a PR, but since the author has been off GitHub for 11 months I think it might be better to import a fork, or just copy in the relevant parts since it's MIT.

**Pull request merged**
